class ChangeAutoGeneratedToStringOnCourses < ActiveRecord::Migration[8.1]
  def up
    remove_column :courses, :auto_generated
    add_column :courses, :auto_generated, :string, null: false, default: "none"
  end

  def down
    remove_column :courses, :auto_generated
    add_column :courses, :auto_generated, :boolean, null: false, default: false
  end
end
